### ISSUE TITLE
Error: sed: can't read /var/ASCIoTAgent/LocalConfiguration.json: No such file or directory

### ISSUE THREAD

**Issue by ksaye** [Azure/Azure-IoT-Security-Agent-C#6]
Trying out Azure Security Center, the installation is failing.

root@nuc:~/Azure-IoT-Security-Agent-C/src/installation# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

Steps to repor:

1. git clone https://github.com/Azure/Azure-IoT-Security-Agent-C.git
2. cd ~/Azure-IoT-Security-Agent-C/src/installation
3. (create the the iot device and the azureiotsecurity module, copy down the key)
4. vi ./key and past the key
5. run ./InstallSecurityAgent.sh -aui SecurityModule -aum SymmetricKey -f ./key -hn iotsecuritycenter.azure-devices.net -di nuc -i

and I get the error below:

root@nuc:~/Azure-IoT-Security-Agent-C/src/installation# ./InstallSecurityAgent.sh -aui SecurityModule -aum SymmetricKey -f ./key -hn iotsecuritycenter.azure-devices.net -di nuc -i
installing agent dependencies
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcurl4-openssl-dev is already the newest version (7.58.0-2ubuntu3.7).
uuid-runtime is already the newest version (2.31.1-0.4ubuntu3.3).
The following additional packages will be installed:
  libauparse0
Suggested packages:
  audispd-plugins
The following NEW packages will be installed:
  auditd libauparse0
0 upgraded, 2 newly installed, 0 to remove and 384 not upgraded.
Need to get 242 kB of archives.
After this operation, 803 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 libauparse0 amd64 1:2.8.2-1ubuntu1 [48.6 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 auditd amd64 1:2.8.2-1ubuntu1 [194 kB]
Fetched 242 kB in 1s (364 kB/s)
Selecting previously unselected package libauparse0:amd64.
(Reading database ... 160442 files and directories currently installed.)
Preparing to unpack .../libauparse0_1%3a2.8.2-1ubuntu1_amd64.deb ...
Unpacking libauparse0:amd64 (1:2.8.2-1ubuntu1) ...
Selecting previously unselected package auditd.
Preparing to unpack .../auditd_1%3a2.8.2-1ubuntu1_amd64.deb ...
Unpacking auditd (1:2.8.2-1ubuntu1) ...
Setting up libauparse0:amd64 (1:2.8.2-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-20) ...
Setting up auditd (1:2.8.2-1ubuntu1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/auditd.service → /lib/systemd/system/auditd.service.
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for systemd (237-3ubuntu10.12) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ureadahead (0.100.0-20) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
uuid-runtime is already the newest version (2.31.1-0.4ubuntu3.3).
0 upgraded, 0 newly installed, 0 to remove and 384 not upgraded.
installing agent
creating service user
Adding user `asciotagent' ...
Adding new group `asciotagent' (1001) ...
Adding new user `asciotagent' (1001) with group `asciotagent' ...
Creating home directory `/home/asciotagent' ...
Copying files from `/etc/skel' ...
--2019-08-07 17:15:07--  https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/source/code/plugins/oms_audits.xml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133, 151.101.64.133, 151.101.0.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65026 (64K) [text/plain]
Saving to: ‘/root/Azure-IoT-Security-Agent-C/src/installation/oms_audits.xml’

/root/Azure-IoT-Security-Agent-C/src/installation/oms_audi 100%[======================================================================================================================================>]  63.50K  --.-KB/s    in 0.02s

2019-08-07 17:15:08 (3.33 MB/s) - ‘/root/Azure-IoT-Security-Agent-C/src/installation/oms_audits.xml’ saved [65026/65026]

--2019-08-07 17:15:08--  https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/source/code/plugins/omsbaseline_x64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133, 151.101.64.133, 151.101.0.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8329965 (7.9M) [application/octet-stream]
Saving to: ‘/root/Azure-IoT-Security-Agent-C/src/installation/omsbaseline’

/root/Azure-IoT-Security-Agent-C/src/installation/omsbasel 100%[======================================================================================================================================>]   7.94M  7.49MB/s    in 1.1s

2019-08-07 17:15:09 (7.49 MB/s) - ‘/root/Azure-IoT-Security-Agent-C/src/installation/omsbaseline’ saved [8329965/8329965]

sed: can't read /var/ASCIoTAgent/LocalConfiguration.json: No such file or directory
sed: can't read /var/ASCIoTAgent/LocalConfiguration.json: No such file or directory
sed: can't read /var/ASCIoTAgent/LocalConfiguration.json: No such file or directory
sed: can't read /var/ASCIoTAgent/LocalConfiguration.json: No such file or directory
sed: can't read /var/ASCIoTAgent/LocalConfiguration.json: No such file or directory
sed: can't read /var/ASCIoTAgent/LocalConfiguration.json: No such file or directory
chown: cannot access '/var/ASCIoTAgent/ASCIoTAgent': No such file or directory
chmod: cannot access '/var/ASCIoTAgent/ASCIoTAgent': No such file or directory
Created symlink /etc/systemd/system/default.target.wants/ASCIoTAgent.service → /etc/systemd/system/ASCIoTAgent.service.
agent installation finished
root@nuc:~/Azure-IoT-Security-Agent-C/src/installation# systemctl status ASCIoTAgent.service
● ASCIoTAgent.service - Azure Security Center for IoT Agent
   Loaded: loaded (/etc/systemd/system/ASCIoTAgent.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-08-07 17:17:04 CDT; 5s ago
  Process: 25437 ExecStart=/var/ASCIoTAgent/ASCIoTAgent (code=exited, status=203/EXEC)
 Main PID: 25437 (code=exited, status=203/EXEC)

Aug 07 17:17:04 nuc systemd[1]: ASCIoTAgent.service: Main process exited, code=exited, status=203/EXEC
Aug 07 17:17:04 nuc systemd[1]: ASCIoTAgent.service: Failed with result 'exit-code'.
root@nuc:~/Azure-IoT-Security-Agent-C/src/installation# ls /var/ASCIoTAgent/
ASCIoTAgent.service      InstallSecurityAgent.sh  key                      oms_audits.xml           omsbaseline
root@nuc:~/Azure-IoT-Security-Agent-C/src/installation#

root@nuc:~/Azure-IoT-Security-Agent-C/src/installation# systemctl status ASCIoTAgent.service
● ASCIoTAgent.service - Azure Security Center for IoT Agent
   Loaded: loaded (/etc/systemd/system/ASCIoTAgent.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-08-07 17:25:16 CDT; 1s ago
  Process: 27269 ExecStart=/var/ASCIoTAgent/ASCIoTAgent (code=exited, status=203/EXEC)
 Main PID: 27269 (code=exited, status=203/EXEC)

Aug 07 17:25:16 nuc systemd[27269]: ASCIoTAgent.service: Failed at step EXEC spawning /var/ASCIoTAgent/ASCIoTAgent: No such file or directory
Aug 07 17:25:16 nuc systemd[1]: ASCIoTAgent.service: Main process exited, code=exited, status=203/EXEC
Aug 07 17:25:16 nuc systemd[1]: ASCIoTAgent.service: Failed with result 'exit-code'.

**Comment by mcrlc** [comment]
Thanks for the feedback!
It looks like you were trying to install the agent without building it first. You can either build it from the source code, or download the latest release from this link:
https://github.com/Azure/Azure-IoT-Security-Agent-C/releases/latest

**Comment by ksaye** [comment]
That did it, thanks.
